### PR TITLE
Expert Refactor (by an expert)

### LINKED ISSUE #3: wrong return type for u8 array
https://github.com/coolaj86/zig-uuidv7/blob/02d997d22acf304c518313e91503b4ccef091b8e/uuidv7.zig#L65-L70

> Just so ya know, the reason why this is a use-after-free is because you are returning a slice ([]const u8), i.e. a ptr+len, to a stack-allocated array that dies on function return. If you return the array instead, i.e. [32]u8, that has "by-value" semantics, then that does what you expect.

### PR DESCRIPTION
**Pull request by Validark**
This is optimized for simplicity of implementation, not speed.

If you did want to optimize the hex-printer for speed, you would expand 16 bytes into 32 nibbles, then coerce that to 32 bytes. Currently, LLVM does not know how to do `@as(@Vector(32, u8), @as(@Vector(32, u4), @bitCast(x)))` efficiently (https://github.com/llvm/llvm-project/issues/79094). [Here is the workaround](https://gist.github.com/Validark/e94d1f6ea4b132cfaa839be5069dde6a). Then you would do a `vpshufb` on x86/`tbl` on ARM to lookup each nibble into a table of `{ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f' }`. Unfortunately my cross-platform implementation that handles vector shuffles got deleted by accident, so I won't provide code for that here today. Then you could use a vector permute or vector expansion to provide enough space for the dashes, and merge them in. Let me know if you would prefer a version optimized for speed.

Fixes https://github.com/coolaj86/zig-uuidv7/issues/3

### CODE REVIEW

File: uuidv7.zig [hunk 1]
```diff
@@ -4,67 +4,56 @@
...
+    rand_b: u62,
+
+    fn toString(self: @This()) ![36]u8 {
+        // time_h32-t_16-verh-varh-rand03rand04
+        // 019212d3-87f4-7d25-902e-b8d39fe07f08
+        const hex = std.fmt.hex(@as(u128, @bitCast(self)));
+        var buffer: [36]u8 = undefined;
+
+        _ = try std.fmt.bufPrint(&buffer, "{s}-{s}-{s}-{s}-{s}", .{
+            hex[0..][0..8].*,
```
Comment (coolaj86) [inline uuidv7.zig:38]: I've never seen syntax like this before.

As per our discussion, this would be the same:

```zig
hex[0..8].*,
hex[8..12].*,
hex[12..16].*,
hex[16..20].*,
hex[20..32].*,
```

The double indexing is to show the lengths. It could be done any number of times, albeit nonsensical:

```zig
hex[12..][0..4][0..4][0..4][0..4][0..4][0..4].*,
```

The `.*` is making a copy.

Comment (Validark) [reply uuidv7.zig:38]: Updated according to your preferences

**Comment by coolaj86** [comment]
I left it the way you originally did it. I wasn't requesting a change, I just didn't understand.

Thank you.

File: uuidv7.zig (hunk 1 above)
Comment (coolaj86) [reply uuidv7.zig:38]: NO! Reverted to how you did it. I will learn at the feet of the master.
